// Generated by CoffeeScript 1.3.3
(function() {

  require("zappa")(process.argv[2], function() {
    return this.app.get('/', function(req, res) {
      return res.send('boring! test!!! ektaAdd some excitement');
    });
  });

}).call(this);
